apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "imagenet-vit"
  annotations:
    serving.kserve.io/enable-metric-aggregation: "true"
    serving.kserve.io/enable-prometheus-scraping: "true"
    autoscaling.knative.dev/target: "1"
spec:
  predictor:
    # minReplicas: 0
    # maxReplicas: 10
    # containerConcurrency: 10
    canaryTrafficPercent: 30
    serviceAccountName: s3-read-only
    pytorch:
      protocolVersion: v1
      # storageUri: s3://cr-tsai-emlo/kserve-ig/imagenet-vit/
      storageUri: s3://cr-tsai-emlo/kserve-ig/cat-classifier/
      image: pytorch/torchserve-kfs:0.12.0
      resources:
        limits:
          cpu: 2600m
          memory: 4Gi
      env:
        - name: TS_DISABLE_TOKEN_AUTHORIZATION
          value: "true"
